apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJhcnRpZmFjdG9yeS5kZXZvcHMuZGV2LmxvY2FsIjoge30sCgkJImdoY3IuaW8iOiB7CgkJCSJhdXRoIjogIllYSmxabVYyT21kb2NGOUdaSE5OTlVjMlFrVktNM0pvVmxGSlJGcHBWMDFhT0Roc1IxbENWa296V0dWM01Yaz0iCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjoge30sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxL2FjY2Vzcy10b2tlbiI6IHt9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS9yZWZyZXNoLXRva2VuIjoge30sCgkJInJlcG8uZGV2b3BzLmRldi5sb2NhbCI6IHt9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcC5leGUiCn0K
type: kubernetes.io/dockerconfigjson
